# Generated by Django 5.0.6 on 2024-08-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='votingevent',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
