# Generated by Django 5.0.6 on 2024-08-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_pics/'),
        ),
    ]
