# Generated by Django 5.1 on 2024-08-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_category_votingevent_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='votingevent',
            old_name='is_anonymous',
            new_name='is_private',
        ),
        migrations.RemoveField(
            model_name='votingevent',
            name='event_token',
        ),
    ]
