# Generated by Django 5.1 on 2024-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_rename_bio_candidate_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voter_is_anonymous',
            new_name='is_anonymous',
        ),
        migrations.AddField(
            model_name='votingevent',
            name='candidate_numbers',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='votingevent',
            name='event_token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
