# Generated by Django 5.0.6 on 2024-08-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_rename_voter_is_anonymous_vote_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingevent',
            name='event_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
